apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mirroring
  name: mirroring-tomcat-web
  annotations: {}
spec:
  selector:
    matchLabels:
      app: mirroring-tomcat-web
  replicas: 3
  template:
    metadata:
      labels:
        app: mirroring-tomcat-web
    spec:
      containers:
        - name: container
          image: >-
            028954022636.dkr.ecr.ap-northeast-2.amazonaws.com/application:tomcat1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
