apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-web-tomcat
  name: test-web-svc
  namespace: test-web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-web-tomcat
  clusterIP: 10.100.150.100
